import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [factions, setFactions] = useState<unknown[]>([]);

  useEffect(() => {
    fetch("/api/hello")
      .then((res) => res.json())
      .then((data) => setFactions(data));
  }, []);

  return (
    <>
      <Head>
        <title>Warhammer Sim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Factions</h1>
        <ul>
          {factions.map((faction, index) => (
            <li key={index}>{JSON.stringify(faction)}</li>
          ))}
        </ul>
      </div>
    </>
  );
}
