import Head from "next/head";
//import { useEffect, useState } from "react";
import PanelLeft from "./App/PanelLeft/component";
import PanelRight from "./App/PanelRight/component";

export default function Home() {
  // const [factions, setFactions] = useState<unknown[]>([]);
  // const [models, setModels] = useState<unknown[]>([]);

  // useEffect(() => {
  //   fetch("/api/provide_factions")
  //     .then((res) => res.json())
  //     .then((data) => setFactions(data));

  //   fetch("/api/provide_models")
  //     .then((res) => res.json())
  //     .then((data) => setModels(data));

  // }, []);

  return (
    // <>
    //   <Head>
    //     <title>Warhammer Sim</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <div>
    //     <h1>Factions</h1>
    //     <ul>
    //       {factions.map((faction, index) => (
    //         <li key={index}>{JSON.stringify(faction)}</li>
    //       ))}
    //     </ul>
    //   </div>
    //   <div>
    //     <h1>Models</h1>
    //     <ul>
    //       {models.map((faction, index) => (
    //         <li key={index}>{JSON.stringify(faction)}</li>
    //       ))}
    //     </ul>
    //   </div>
    // </>

    <>
      <Head>
        <title>Warhammer Sim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: 'flex' }}>
        <PanelLeft />
        <PanelRight />
      </div>
    </>
  );
}
